# Generated by Django 2.2 on 2019-07-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrainparkour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='signId',
            field=models.IntegerField(db_column='signid'),
        ),
    ]
