# Generated by Django 2.2 on 2019-07-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrainparkour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='raceMilliseconds',
            field=models.IntegerField(db_column='racemilliseconds'),
        ),
    ]
