# Generated by Django 2.2 on 2019-07-07 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrainparkour', '0002_auto_20190706_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='calcFinds',
            field=models.IntegerField(db_column='calcfinds', default=0),
        ),
        migrations.AlterField(
            model_name='sign',
            name='calcNearest',
            field=models.ForeignKey(db_column='calcnearest_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nearest_to', to='terrainparkour.Sign'),
        ),
    ]
