# Generated by Django 2.2 on 2019-07-07 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrainparkour', '0003_auto_20190706_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionresultsent',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='actionresultssent', to='terrainparkour.RobloxUser'),
        ),
    ]
