# Generated by Django 2.2 on 2019-07-07 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrainparkour', '0006_auto_20190706_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, related_name='chatmessages', to='terrainparkour.RobloxUser'),
        ),
    ]
