# Generated by Django 2.2 on 2019-07-07 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrainparkour', '0007_auto_20190706_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionresultsent',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='actionresultssent', to='terrainparkour.RobloxUser'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='assetId',
            field=models.IntegerField(db_column='asset_id'),
        ),
        migrations.AlterField(
            model_name='badgegrant',
            name='badge',
            field=models.ForeignKey(db_column='badge_id', on_delete=django.db.models.deletion.CASCADE, related_name='badgegrants', to='terrainparkour.Badge'),
        ),
        migrations.AlterField(
            model_name='badgegrant',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='badgegrants', to='terrainparkour.RobloxUser'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='requestsource',
            field=models.ForeignKey(db_column='requestsource_id', on_delete=django.db.models.deletion.CASCADE, related_name='chatmessages', to='terrainparkour.RequestSource'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='chatmessages', to='terrainparkour.RobloxUser'),
        ),
    ]
