# Generated by Django 2.2 on 2019-07-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrainparkour', '0008_auto_20190706_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='assetId',
            field=models.IntegerField(db_column='assetid'),
        ),
    ]
