# Generated by Django 2.2 on 2019-07-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrainparkour', '0009_auto_20190706_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robloxuser',
            name='userId',
            field=models.IntegerField(db_column='userid', unique=True),
        ),
    ]
