# Generated by Django 2.2 on 2019-07-07 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrainparkour', '0010_auto_20190706_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestrun',
            name='race',
            field=models.ForeignKey(db_column='race_id', on_delete=django.db.models.deletion.CASCADE, related_name='bestruns', to='terrainparkour.Race'),
        ),
        migrations.AlterField(
            model_name='bestrun',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='bestruns', to='terrainparkour.RobloxUser'),
        ),
    ]
