# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-17 20:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

    ]
