# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='signid',
            new_name='signId',
        ),
    ]
