# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0002_auto_20170518_0552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='racemilliseconds',
            new_name='raceMilliseconds',
        ),
    ]
