# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-18 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0002_auto_20180317_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionResultSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=300)),
                ('notifyAllExcept', models.BooleanField()),
                ('notify', models.BooleanField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='actionresultssent', to='terrainapp.RobloxUser')),
            ],
            options={
                'db_table': 'actionresultsent',
            },
        ),
    ]
