# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-18 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0004_badgegrant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tixtransaction',
            old_name='reason',
            new_name='targetType',
        ),
        migrations.AddField(
            model_name='raceevent',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tixtransaction',
            name='targetId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raceevent',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raceevents', to='terrainapp.Race'),
        ),
    ]
