# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-18 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0004_auto_20180317_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tixtransaction',
            old_name='day',
            new_name='transactionday',
        ),
    ]
