# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0004_bestrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
