# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-18 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0005_auto_20180317_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionResultSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=300)),
                ('notify', models.BooleanField()),
                ('notifyAllExcept', models.BooleanField()),
                ('userId', models.IntegerField()),
            ],
            options={
                'db_table': 'actionresultsent',
            },
        ),
    ]
