# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0006_auto_20170520_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestrun',
            old_name='rank',
            new_name='place',
        ),
    ]
