# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-18 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0006_auto_20180318_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceevent',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raceevents', to='terrainapp.Badge'),
        ),
        migrations.AlterField(
            model_name='raceevent',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
