# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-23 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0007_auto_20180318_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceEventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'raceeventtype',
            },
        ),
        migrations.AddField(
            model_name='raceevent',
            name='eventtype',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='terrainapp.RaceEventType'),
        ),
    ]
