# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0007_auto_20170520_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='X',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sign',
            name='Y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sign',
            name='Z',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
