# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0008_auto_20170520_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='X',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='sign',
            old_name='Y',
            new_name='y',
        ),
        migrations.RenameField(
            model_name='sign',
            old_name='Z',
            new_name='z',
        ),
    ]
