# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0009_auto_20170520_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deaths', to='terrainapp.RobloxUser')),
            ],
            options={
                'db_table': 'userdied',
            },
        ),
    ]
