# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0010_userdied'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdied',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdied',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdied',
            name='z',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
