# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0012_userreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedSecurityAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'failedsecurityattempt',
            },
        ),
        migrations.CreateModel(
            name='RequestSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'requestsource',
            },
        ),
        migrations.AddField(
            model_name='failedsecurityattempt',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='terrainapp.RequestSource'),
        ),
    ]
