# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0013_auto_20170524_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedsecurityattempt',
            name='params',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='requestsource',
            name='failure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestsource',
            name='success_count',
            field=models.IntegerField(default=0),
        ),
    ]
