# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0014_auto_20170524_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersources', to='terrainapp.RequestSource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersources', to='terrainapp.RobloxUser')),
            ],
            options={
                'db_table': 'usersource',
            },
        ),
    ]
