# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0015_usersource'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersource',
            name='first',
            field=models.BooleanField(default=0),
        ),
    ]
