# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0016_usersource_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quits', to='terrainapp.RobloxUser')),
            ],
            options={
                'db_table': 'userquit',
            },
        ),
    ]
