# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0017_userquit'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='place',
            field=models.IntegerField(default=0),
        ),
    ]
