# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0018_run_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rawtext', models.CharField(max_length=500)),
                ('filteredtext', models.CharField(max_length=500)),
                ('requestsource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatmessages', to='terrainapp.RequestSource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatmessages', to='terrainapp.RobloxUser')),
            ],
            options={
                'db_table': 'chatmessage',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=200)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='terrainapp.RobloxUser')),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
