# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0019_chatmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='calcFinds',
            field=models.IntegerField(default=0),
        ),
    ]
