# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0021_gameservererror'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameservererror',
            name='requestsource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gameservererrors', to='terrainapp.RequestSource'),
        ),
    ]
