# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0023_race_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='robloxuser',
            name='banlevel',
            field=models.IntegerField(default=0),
        ),
    ]
