# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0024_robloxuser_banlevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robloxuser',
            old_name='banlevel',
            new_name='banLevel',
        ),
        migrations.AddField(
            model_name='sign',
            name='calcNearest',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nearest_to', to='terrainapp.Sign'),
        ),
    ]
