# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0025_auto_20170608_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('daystr', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'day',
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'power',
            },
        ),
        migrations.CreateModel(
            name='UserPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpowers', to='terrainapp.Day')),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpowers', to='terrainapp.Power')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpowers', to='terrainapp.RobloxUser')),
            ],
            options={
                'db_table': 'userpower',
            },
        ),
    ]
