# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-12 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0026_day_power_userpower'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestrun',
            name='speed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='speed',
            field=models.FloatField(default=0),
        ),
    ]
