# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-13 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0027_auto_20180311_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('assetId', models.IntegerField()),
            ],
            options={
                'db_table': 'badge',
            },
        ),
        migrations.CreateModel(
            name='RaceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='terrainapp.Badge')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='terrainapp.Race')),
            ],
            options={
                'db_table': 'raceevent',
            },
        ),
    ]
