# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-13 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0028_badge_raceevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceevent',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='raceevent',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
