# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-15 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0029_auto_20180312_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamejoin',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
