# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-16 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0030_gamejoin_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameleave',
            name='user',
        ),
        migrations.DeleteModel(
            name='GameLeave',
        ),
    ]
