# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-16 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrainapp', '0031_auto_20180316_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamejoin',
            name='left',
            field=models.DateTimeField(default=None),
        ),
    ]
