version: 3

pullapprove_conditions:
- "'WIP' not in title"
- "base.ref == 'master'"

notifications:
- when: pull_request.opened
  comment: >
    Hey @{{ author }}, new PR has been detected by PullApprove!

    Thanks for the PR!
- when: pullapprove.approved
  comment: "The review is completed. @ernop, please merge this in when ready."

groups:
  code:
    conditions:
    - "'*.cs' in files"
    reviewers:
      users:
      - ernop
      - ernopms
    reviews:
      required: 1  # number of approvals required from this group
      request: 1  # number of review requests sent at a time
      request_order: random  # "random" or "given"
  css:
    conditions:
    - "'*.css' in files"
    reviewers:
      users:
      - ernop
      - ernopms
    reviews:
      required: 1  # number of approvals required from this group
      request: 1  # number of review requests sent at a time
      request_order: random  # "random" or "given"