version: '3'

services:
  db:
    image: postgres
    container_name: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: terrainparkour
  web:
    build: image
    container_name: django
    #command: gunicorn terrainparkour.wsgi -b 0.0.0.0:8000
    #command: gunicorn app:app -b 0.0.0.0:8000 #run a simple web server that returns okay for everything.
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn terrainparkour.wsgi -b 0.0.0.0:8001"  
    #command: python manage.py runserver  0.0.0.0:8001
    volumes:
      - ./image/terrainparkour:/code
      - ./image/terrainparkour/static:/static    #copy files to static directory whenever web starts up.
    restart: always
    depends_on:
      - db
  nginx:
    container_name: nginx
    build: nginx
    image: nginx:1.13-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx:/config
      - ./image/terrainparkour/static:/static
    depends_on:
      - web