from terrainapp.admin.BadgeAdmin import BadgeAdmin
from terrainapp.admin.BestRunAdmin import BestRunAdmin
from terrainapp.admin.ChatMessageAdmin import ChatMessageAdmin
from terrainapp.admin.FailedSecurityAttemptAdmin import FailedSecurityAttemptAdmin
from terrainapp.admin.FindAdmin import FindAdmin
from terrainapp.admin.GameJoinAdmin import GameJoinAdmin
from terrainapp.admin.GameServerErrorAdmin import GameServerErrorAdmin
#from terrainapp.admin.PowerAdmin import PowerAdmin
from terrainapp.admin.SignAdmin import SignAdmin
from terrainapp.admin.RaceAdmin import RaceAdmin
from terrainapp.admin.RaceEventAdmin import RaceEventAdmin
from terrainapp.admin.RequestSourceAdmin import RequestSourceAdmin
from terrainapp.admin.RunAdmin import RunAdmin
from terrainapp.admin.RobloxUserAdmin import RobloxUserAdmin
from terrainapp.admin.UserDiedAdmin import UserDiedAdmin
#from terrainapp.admin.UserPowerAdmin import UserPowerAdmin
from terrainapp.admin.UserResetAdmin import UserResetAdmin
from terrainapp.admin.UserSourceAdmin import UserSourceAdmin
from terrainapp.admin.UserQuitAdmin import UserQuitAdmin
